[package]
name = "itmsink"
version = "0.1.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/drone-os/itmsink"
description = "ITM protocol parser."

[dependencies]
clap-verbosity-flag = "0.2"
exitfailure = "0.5"
failure = { version = "0.1", features = ["derive"] }
log = "0.4"
smallvec = "0.6"
structopt = "0.2"
